class Solution {
	    public int countKDifference(int[] nums, int k) {
		            
		            // time : O(n^2) space : O(1) 
			    //         //using 2 for loops and check the diff = k if then increase count and return
			    //                 
			    //                         // time : O(n) space : O(n) 
			    //                                 /*int count = 0;
			    //                                         int[] memory = new int[101];
			    //                                                 for(int i : nums) {
			    //                                                             if( i + k <= 100 )
			    //                                                                             count += memory[i + k];
			    //
			    //                                                                                         if( i - k >= 1)
			    //                                                                                                         count += memory[i - k];
			    //
			    //                                                                                                                     memory[i]++;
			    //                                                                                                                             }
			    //                                                                                                                                     return count;
			    //                                                                                                                                             */
			    //                                                                                                                                                     
			    //                                                                                                                                                             // USING HASHMAP
			    //                                                                                                                                                                     // time  :O(n) space:O(n)
			    //                                                                                                                                                                              Map<Integer, Integer> hm = new HashMap<>();
			    //                                                                                                                                                                                      
			    //                                                                                                                                                                                              for(int i : nums){
			    //                                                                                                                                                                                                          hm.put(i, hm.getOrDefault(i,0)+1);
			    //                                                                                                                                                                                                                  }
			    //                                                                                                                                                                                                                          
			    //                                                                                                                                                                                                                                  int res = 0;
			    //                                                                                                                                                                                                                                          for(int key: hm.keySet()){
			    //                                                                                                                                                                                                                                                      int target1 = key - k;
			    //                                                                                                                                                                                                                                                                  int target2 = key + k;
			    //                                                                                                                                                                                                                                                                              
			    //                                                                                                                                                                                                                                                                                          if(hm.containsKey(target1)) res += hm.get(target1)*hm.get(key);            
			    //                                                                                                                                                                                                                                                                                                      if(hm.containsKey(target2)) res += hm.get(target2)*hm.get(key);
			    //                                                                                                                                                                                                                                                                                                              }
			    //                                                                                                                                                                                                                                                                                                                      
			    //                                                                                                                                                                                                                                                                                                                      		// the number of pairs was double counted in the for loop.
			    //                                                                                                                                                                                                                                                                                                                      		        return res/2;
			    //                                                                                                                                                                                                                                                                                                                      		                
			    //                                                                                                                                                                                                                                                                                                                      		                        
			    //                                                                                                                                                                                                                                                                                                                      		                                
			    //                                                                                                                                                                                                                                                                                                                      		                                        /*
			    //                                                                                                                                                                                                                                                                                                                      		                                                int[] arr = new int[101];
			    //                                                                                                                                                                                                                                                                                                                      		                                                        
			    //                                                                                                                                                                                                                                                                                                                      		                                                                for(int i=0;i<nums.length;i++){
			    //                                                                                                                                                                                                                                                                                                                      		                                                                            
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                        int no = nums[i];
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                    
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                arr[no]++;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                        }
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                        int currInd = 0;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                int totalCount = 0;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                        while(currInd<101){
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                    
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                if(arr[currInd]!=0){
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                int newInd = currInd;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                while((newInd+k)<101){
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                    totalCount = totalCount+ (arr[newInd]*arr[newInd+k]);
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                        newInd+=k;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                        }
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                    }else{
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                    currInd++;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                }
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                            
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                        currInd++;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                }
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                        
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                                return totalCount;
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                                        
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                                                */
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                                                    }
			    //                                                                                                                                                                                                                                                                                                                      		                                                                                                                                                                                                                                                                                                                                                                                                    }
